on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://dev.qhpassist.com/api/swagger/v1/swagger.json'
          cmd_options: '-a'
