on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # The OpenAPI definition URL (Swagger)
          target: 'https://dev.qhpassist.com/api/swagger/v1/swagger.json'
          # Options to include alpha rules and generate reports
          cmd_options: '-r zap_report.html'
